server:
  port: ${PORT:8085}  # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL:http://localhost:8085}  # Valor por defecto si SERVER_URL no está configurado

spring:
  application:
    name: age-detector
  r2dbc:
    url: r2dbc:postgresql://ep-spring-mode-a839f09f-pooler.eastus2.azure.neon.tech/age_detector
    username: neondb_owner
    password: npg_IJdQEZuF4BN3
    properties:
      sslmode: require
      channelBinding: require

rapidapi:
  url: https://age-detector.p.rapidapi.com
  host: age-detector.p.rapidapi.com
  apikey: 19563912e8msh910ec9423e2adbep1052e9jsn390a6a17afd4

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
