server:
  port: ${PORT:8085}  # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL:http://localhost:8085}  # Valor por defecto si SERVER_URL no está configurado

spring:
  application:
    name: image-Generator
  r2dbc:
    url: r2dbc:postgresql://ep-spring-mode-a839f09f-pooler.eastus2.azure.neon.tech:5432/image_generator?ssl=true
    username: neondb_owner
    password: npg_IJdQEZuF4BN3
    pool:
      validation-query: SELECT 1
      max-idle-time: 30m

rapidapi:
  url: https://ai-text-to-image-generator-flux-free-api.p.rapidapi.com
  host: ai-text-to-image-generator-flux-free-api.p.rapidapi.com
  apikey: 19563912e8msh910ec9423e2adbep1052e9jsn390a6a17afd4

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
