server:
  port: ${PORT:8085}
  url: ${SERVER_URL:http://localhost:8085}

spring:
  application:
    name: ai-chatbot

  r2dbc:
    url: r2dbc:postgresql://ep-spring-mode-a839f09f-pooler.eastus2.azure.neon.tech/chat_messages?ssl=true
    username: neondb_owner
    password: npg_IJdQEZuF4BN3
    pool:
      validation-query: SELECT 1
      max-idle-time: 30m

rapidapi:
  url: https://ai-chatbot-ai-chatbot-multi-lang.p.rapidapi.com
  host: ai-chatbot-ai-chatbot-multi-lang.p.rapidapi.com
  apikey: 19563912e8msh910ec9423e2adbep1052e9jsn390a6a17afd4

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
