apiVersion: v1
kind: Secret
metadata:
  name: jossue-torres-db-secret
type: Opaque
stringData:
  database-url: "r2dbc:postgresql://ep-spring-mode-a839f09f-pooler.eastus2.azure.neon.tech/chat_messages?ssl=true"
  database-username: "neondb_owner"
  database-password: "npg_IJdQEZuF4BN3"
