apiVersion: v1
kind: Service
metadata:
  name: jossue-torres-front-service
spec:
  type: NodePort
  selector:
    app: jossue-torres-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
