name: Docker Hub



on:
  push:
    branches:
      - main
      - main # puedes añadir más ramas
  pull_request:
    branches:
      - main
      - main # puedes añadir más ramas
  schedule:
    # Ejecutar todos los días a las 8:00 AM hora Perú (UTC-5) → 1:00 PM UTC
    - cron: '0 13 * * *'
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions UI


jobs:
  dockerhub:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - name: Checkout Repository
        uses: actions/checkout@v3


      # 2. Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # 3. Build y Push con tags latest y SHA
      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/image_generator:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/image_generator:${{ github.sha }}




#┌───────────── minuto (0 - 59)
#│ ┌───────────── hora (0 - 23)
#│ │ ┌───────────── día del mes (1 - 31)
#│ │ │ ┌───────────── mes (1 - 12)
#│ │ │ │ ┌───────────── día de la semana (0 - 6 → domingo=0)
#│ │ │ │ │
#│ │ │ │ │
#* * * * *
