name: Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Ejecutar todos los días a las 8:00 AM hora Perú (UTC-5) → 1:00 PM UTC
    - cron: '0 13 * * *'
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions UI

jobs:
  dockerhub:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build y Push de la imagen Docker
      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .            # raíz del repositorio
          file: ./Dockerfile    # Dockerfile en la raíz
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/as232s5_aej_14-be:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/as232s5_aej_14-be:${{ github.sha }}
